services:
  minirootfs:
    image: ghcr.io/kou029w/yama/minirootfs
    volumes:
      - ./cache:/etc/apk/cache
      - ./src/rootfs/etc/apk/repositories:/etc/apk/repositories
      - ./src/rootfs/etc/apk/world:/etc/apk/world
  builder:
    image: ghcr.io/kou029w/yama/minirootfs
    volumes:
      - ./cache:/etc/apk/cache
      - ./src/rootfs/etc/apk/repositories:/etc/apk/repositories
      - ./src/rootfs/etc/apk/world:/etc/apk/world
      - ./fstab:/etc/fstab
      - ./dist/overlay.img:/overlay.img
    privileged: true
    command: |
      sh -c '
        mkdir -p /mnt/overlay
        mount -a \
          && apk add g++ linux-headers make nodejs npm python3
      '
