name: build
on:
  push:
    branches: [main]
  release:
    types: [published]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install -y qemu-user-static
      - run: sudo bin/build
      - uses: actions/upload-artifact@v3
        with:
          name: yama-armhf
          path: yama-armhf.*
  release:
    if: github.event.release.prerelease
    needs: main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: yama-armhf
      - uses: actions/github-script@v6
        with:
          script: |
            const release = require("./.github/scripts/release.js");
            await release({ github, context, glob });
